sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull osrf/ros:melodic-desktop-full
- docker run -d osrf/ros:melodic-desktop-full /bin/bash

script:
- mkdir ./build
- cd ./build
- cmake ..
- make

